/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * configuracion.java
 *
 * Created on 14-mar-2015, 12:55:23
 */
package empleados.modulos.config;

import empleados.modulos.gestionempleados.gestionEF.vista.*;
import empleados.modulos.gestionempleados.gestionEF.modelo.BLL.EFBLLgrafica;
import empleados.Mainapli;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author damian
 */
public class configuracion extends javax.swing.JFrame {

    /** Creates new form configuracion */
    public configuracion() {
        initComponents();
       
        /*this.setTitle("Configuracion");
	this.setLocationRelativeTo(null);
	this.setSize(525,425);//ancho x alto
	this.setResizable(false);
	Image icono=Toolkit.getDefaultToolkit().getImage("imprimir/new.png");
	this.setIconImage(icono);
	this.setExtendedState(JFrame.MAXIMIZED_BOTH); //la aplicación se abre maximizada
        

        
        
        this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
		addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                JOptionPane.showMessageDialog(null,"Saliendo de la aplicación");
                dispose();
                EFBLLgrafica.GuardarSinEnterarse();
                System.exit(0);
            }
        });
	*/	
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FondoConfig = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        Archivo = new javax.swing.JMenu();
        Volver = new javax.swing.JMenuItem();
        Moneda = new javax.swing.JMenu();
        Euros = new javax.swing.JMenuItem();
        Libras = new javax.swing.JMenuItem();
        Dolares = new javax.swing.JMenuItem();
        Decimales = new javax.swing.JMenu();
        UnDecimal = new javax.swing.JMenuItem();
        DosDecimales = new javax.swing.JMenuItem();
        Ficheros = new javax.swing.JMenu();
        JSON = new javax.swing.JMenuItem();
        XML = new javax.swing.JMenuItem();
        TXT = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout FondoConfigLayout = new javax.swing.GroupLayout(FondoConfig);
        FondoConfig.setLayout(FondoConfigLayout);
        FondoConfigLayout.setHorizontalGroup(
            FondoConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        FondoConfigLayout.setVerticalGroup(
            FondoConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        Archivo.setText("Archivo");

        Volver.setText("Volver");
        Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverActionPerformed(evt);
            }
        });
        Archivo.add(Volver);

        jMenuBar1.add(Archivo);

        Moneda.setText("Moneda");

        Euros.setText("Euros €");
        Euros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EurosActionPerformed(evt);
            }
        });
        Moneda.add(Euros);

        Libras.setText("Libras £");
        Libras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LibrasActionPerformed(evt);
            }
        });
        Moneda.add(Libras);

        Dolares.setText("Dolares $");
        Dolares.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DolaresActionPerformed(evt);
            }
        });
        Moneda.add(Dolares);

        jMenuBar1.add(Moneda);

        Decimales.setText("Decimales");

        UnDecimal.setText("0.0");
        UnDecimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UnDecimalActionPerformed(evt);
            }
        });
        Decimales.add(UnDecimal);

        DosDecimales.setText("0.00");
        DosDecimales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DosDecimalesActionPerformed(evt);
            }
        });
        Decimales.add(DosDecimales);

        jMenuBar1.add(Decimales);

        Ficheros.setText("Tipo Fichero");

        JSON.setText("JSON");
        JSON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JSONActionPerformed(evt);
            }
        });
        Ficheros.add(JSON);

        XML.setText("XML");
        XML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XMLActionPerformed(evt);
            }
        });
        Ficheros.add(XML);

        TXT.setText("TXT");
        TXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTActionPerformed(evt);
            }
        });
        Ficheros.add(TXT);

        jMenuBar1.add(Ficheros);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FondoConfig, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FondoConfig, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverActionPerformed
// TODO add your handling code here:
    //dispose();
    //new subprincipal().setVisible(true);
}//GEN-LAST:event_VolverActionPerformed

private void EurosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EurosActionPerformed
// TODO add your handling code here:
    //menuempleados.conf.setMoneda('€');
}//GEN-LAST:event_EurosActionPerformed

private void LibrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LibrasActionPerformed
// TODO add your handling code here:
    //menuempleados.conf.setMoneda('£');
}//GEN-LAST:event_LibrasActionPerformed

private void DolaresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DolaresActionPerformed
// TODO add your handling code here:
    //menuempleados.conf.setMoneda('$');
}//GEN-LAST:event_DolaresActionPerformed

private void UnDecimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UnDecimalActionPerformed
// TODO add your handling code here:
    //menuempleados.conf.setDecimales(1);
}//GEN-LAST:event_UnDecimalActionPerformed

private void DosDecimalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DosDecimalesActionPerformed
// TODO add your handling code here:
    //menuempleados.conf.setDecimales(2);
}//GEN-LAST:event_DosDecimalesActionPerformed

private void JSONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JSONActionPerformed
// TODO add your handling code here:
   //menuempleados.conf.setFichero(1);
    
}//GEN-LAST:event_JSONActionPerformed

private void XMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XMLActionPerformed
// TODO add your handling code here:
    //menuempleados.conf.setFichero(2);
}//GEN-LAST:event_XMLActionPerformed

private void TXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTActionPerformed
// TODO add your handling code here:
    //menuempleados.conf.setFichero(3);
}//GEN-LAST:event_TXTActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JMenu Archivo;
    public static javax.swing.JMenu Decimales;
    public static javax.swing.JMenuItem Dolares;
    public static javax.swing.JMenuItem DosDecimales;
    public static javax.swing.JMenuItem Euros;
    private javax.swing.JMenu Ficheros;
    public static javax.swing.JPanel FondoConfig;
    public static javax.swing.JMenuItem JSON;
    public static javax.swing.JMenuItem Libras;
    private javax.swing.JMenu Moneda;
    public static javax.swing.JMenuItem TXT;
    public static javax.swing.JMenuItem UnDecimal;
    public static javax.swing.JMenuItem Volver;
    public static javax.swing.JMenuItem XML;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
